[package]
name = "paw-structopt"
version = "0.0.0"
authors = ["The Rust CLI Working Group"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
structopt = "0.2.15"
syn = { version = "0.15", features = ["full"] }
proc-macro2 = { version = "0.4.24", features = ["nightly"] }
quote = "0.6"
